// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connection.proto

package connection

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	connectioncontext "github.com/networkservicemesh/networkservicemesh/controlplane/pkg/apis/connectioncontext"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MechanismType int32

const (
	MechanismType_DEFAULT_INTERFACE MechanismType = 0
	MechanismType_KERNEL_INTERFACE  MechanismType = 1
	MechanismType_VHOST_INTERFACE   MechanismType = 2
	MechanismType_MEM_INTERFACE     MechanismType = 3
	MechanismType_SRIOV_INTERFACE   MechanismType = 4
	MechanismType_HW_INTERFACE      MechanismType = 5
)

var MechanismType_name = map[int32]string{
	0: "DEFAULT_INTERFACE",
	1: "KERNEL_INTERFACE",
	2: "VHOST_INTERFACE",
	3: "MEM_INTERFACE",
	4: "SRIOV_INTERFACE",
	5: "HW_INTERFACE",
}

var MechanismType_value = map[string]int32{
	"DEFAULT_INTERFACE": 0,
	"KERNEL_INTERFACE":  1,
	"VHOST_INTERFACE":   2,
	"MEM_INTERFACE":     3,
	"SRIOV_INTERFACE":   4,
	"HW_INTERFACE":      5,
}

func (x MechanismType) String() string {
	return proto.EnumName(MechanismType_name, int32(x))
}

func (MechanismType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{0}
}

type State int32

const (
	State_UP   State = 0
	State_DOWN State = 1
)

var State_name = map[int32]string{
	0: "UP",
	1: "DOWN",
}

var State_value = map[string]int32{
	"UP":   0,
	"DOWN": 1,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}

func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{1}
}

type ConnectionEventType int32

const (
	ConnectionEventType_INITIAL_STATE_TRANSFER ConnectionEventType = 0
	ConnectionEventType_UPDATE                 ConnectionEventType = 1
	ConnectionEventType_DELETE                 ConnectionEventType = 2
)

var ConnectionEventType_name = map[int32]string{
	0: "INITIAL_STATE_TRANSFER",
	1: "UPDATE",
	2: "DELETE",
}

var ConnectionEventType_value = map[string]int32{
	"INITIAL_STATE_TRANSFER": 0,
	"UPDATE":                 1,
	"DELETE":                 2,
}

func (x ConnectionEventType) String() string {
	return proto.EnumName(ConnectionEventType_name, int32(x))
}

func (ConnectionEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{2}
}

type Mechanism struct {
	Type                 MechanismType     `protobuf:"varint,1,opt,name=type,proto3,enum=local.connection.MechanismType" json:"type,omitempty"`
	Parameters           map[string]string `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Mechanism) Reset()         { *m = Mechanism{} }
func (m *Mechanism) String() string { return proto.CompactTextString(m) }
func (*Mechanism) ProtoMessage()    {}
func (*Mechanism) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{0}
}

func (m *Mechanism) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mechanism.Unmarshal(m, b)
}
func (m *Mechanism) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mechanism.Marshal(b, m, deterministic)
}
func (m *Mechanism) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mechanism.Merge(m, src)
}
func (m *Mechanism) XXX_Size() int {
	return xxx_messageInfo_Mechanism.Size(m)
}
func (m *Mechanism) XXX_DiscardUnknown() {
	xxx_messageInfo_Mechanism.DiscardUnknown(m)
}

var xxx_messageInfo_Mechanism proto.InternalMessageInfo

func (m *Mechanism) GetType() MechanismType {
	if m != nil {
		return m.Type
	}
	return MechanismType_DEFAULT_INTERFACE
}

func (m *Mechanism) GetParameters() map[string]string {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type Connection struct {
	Id                                   string                               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NetworkService                       string                               `protobuf:"bytes,2,opt,name=network_service,json=networkService,proto3" json:"network_service,omitempty"`
	Mechanism                            *Mechanism                           `protobuf:"bytes,3,opt,name=mechanism,proto3" json:"mechanism,omitempty"`
	Context                              *connectioncontext.ConnectionContext `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	Labels                               map[string]string                    `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	State                                State                                `protobuf:"varint,6,opt,name=state,proto3,enum=local.connection.State" json:"state,omitempty"`
	SourceNetworkServiceManagerName      string                               `protobuf:"bytes,7,opt,name=source_network_service_manager_name,json=sourceNetworkServiceManagerName,proto3" json:"source_network_service_manager_name,omitempty"`
	DestinationNetworkServiceManagerName string                               `protobuf:"bytes,8,opt,name=destination_network_service_manager_name,json=destinationNetworkServiceManagerName,proto3" json:"destination_network_service_manager_name,omitempty"`
	NetworkServiceEndpointName           string                               `protobuf:"bytes,9,opt,name=network_service_endpoint_name,json=networkServiceEndpointName,proto3" json:"network_service_endpoint_name,omitempty"`
	XXX_NoUnkeyedLiteral                 struct{}                             `json:"-"`
	XXX_unrecognized                     []byte                               `json:"-"`
	XXX_sizecache                        int32                                `json:"-"`
}

func (m *Connection) Reset()         { *m = Connection{} }
func (m *Connection) String() string { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()    {}
func (*Connection) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{1}
}

func (m *Connection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connection.Unmarshal(m, b)
}
func (m *Connection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connection.Marshal(b, m, deterministic)
}
func (m *Connection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connection.Merge(m, src)
}
func (m *Connection) XXX_Size() int {
	return xxx_messageInfo_Connection.Size(m)
}
func (m *Connection) XXX_DiscardUnknown() {
	xxx_messageInfo_Connection.DiscardUnknown(m)
}

var xxx_messageInfo_Connection proto.InternalMessageInfo

func (m *Connection) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Connection) GetNetworkService() string {
	if m != nil {
		return m.NetworkService
	}
	return ""
}

func (m *Connection) GetMechanism() *Mechanism {
	if m != nil {
		return m.Mechanism
	}
	return nil
}

func (m *Connection) GetContext() *connectioncontext.ConnectionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Connection) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Connection) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UP
}

func (m *Connection) GetSourceNetworkServiceManagerName() string {
	if m != nil {
		return m.SourceNetworkServiceManagerName
	}
	return ""
}

func (m *Connection) GetDestinationNetworkServiceManagerName() string {
	if m != nil {
		return m.DestinationNetworkServiceManagerName
	}
	return ""
}

func (m *Connection) GetNetworkServiceEndpointName() string {
	if m != nil {
		return m.NetworkServiceEndpointName
	}
	return ""
}

type ConnectionEvent struct {
	Type                 ConnectionEventType    `protobuf:"varint,1,opt,name=type,proto3,enum=local.connection.ConnectionEventType" json:"type,omitempty"`
	Connections          map[string]*Connection `protobuf:"bytes,2,rep,name=connections,proto3" json:"connections,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ConnectionEvent) Reset()         { *m = ConnectionEvent{} }
func (m *ConnectionEvent) String() string { return proto.CompactTextString(m) }
func (*ConnectionEvent) ProtoMessage()    {}
func (*ConnectionEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{2}
}

func (m *ConnectionEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionEvent.Unmarshal(m, b)
}
func (m *ConnectionEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionEvent.Marshal(b, m, deterministic)
}
func (m *ConnectionEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionEvent.Merge(m, src)
}
func (m *ConnectionEvent) XXX_Size() int {
	return xxx_messageInfo_ConnectionEvent.Size(m)
}
func (m *ConnectionEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionEvent proto.InternalMessageInfo

func (m *ConnectionEvent) GetType() ConnectionEventType {
	if m != nil {
		return m.Type
	}
	return ConnectionEventType_INITIAL_STATE_TRANSFER
}

func (m *ConnectionEvent) GetConnections() map[string]*Connection {
	if m != nil {
		return m.Connections
	}
	return nil
}

func init() {
	proto.RegisterEnum("local.connection.MechanismType", MechanismType_name, MechanismType_value)
	proto.RegisterEnum("local.connection.State", State_name, State_value)
	proto.RegisterEnum("local.connection.ConnectionEventType", ConnectionEventType_name, ConnectionEventType_value)
	proto.RegisterType((*Mechanism)(nil), "local.connection.Mechanism")
	proto.RegisterMapType((map[string]string)(nil), "local.connection.Mechanism.ParametersEntry")
	proto.RegisterType((*Connection)(nil), "local.connection.Connection")
	proto.RegisterMapType((map[string]string)(nil), "local.connection.Connection.LabelsEntry")
	proto.RegisterType((*ConnectionEvent)(nil), "local.connection.ConnectionEvent")
	proto.RegisterMapType((map[string]*Connection)(nil), "local.connection.ConnectionEvent.ConnectionsEntry")
}

func init() { proto.RegisterFile("connection.proto", fileDescriptor_51baa40a1cc6b48b) }

var fileDescriptor_51baa40a1cc6b48b = []byte{
	// 709 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5d, 0x4f, 0xdb, 0x48,
	0x14, 0xc5, 0xce, 0x07, 0xe4, 0x06, 0x88, 0x19, 0x58, 0xd6, 0xeb, 0xdd, 0x15, 0x94, 0x52, 0x35,
	0xa2, 0xaa, 0x53, 0x85, 0x97, 0x52, 0xa9, 0x55, 0x53, 0x32, 0x88, 0x88, 0x24, 0x50, 0xc7, 0x80,
	0x54, 0x55, 0xb2, 0x1c, 0x67, 0x08, 0x16, 0xf6, 0x8c, 0x65, 0x4f, 0x68, 0xf3, 0xd6, 0xf7, 0xfe,
	0xb5, 0xbe, 0xf6, 0xff, 0x54, 0xfe, 0x00, 0x3b, 0x09, 0x0d, 0xea, 0x4b, 0x14, 0x9f, 0x39, 0xe7,
	0xdc, 0x3b, 0xe7, 0xce, 0x0c, 0x48, 0x16, 0xa3, 0x94, 0x58, 0xdc, 0x66, 0x54, 0xf5, 0x7c, 0xc6,
	0x19, 0x92, 0x1c, 0x66, 0x99, 0x8e, 0x9a, 0xe2, 0x8a, 0xec, 0xf1, 0xb1, 0x47, 0x82, 0x1a, 0x71,
	0x3d, 0x3e, 0x8e, 0x7f, 0x63, 0xae, 0xe2, 0x0d, 0x6d, 0x7e, 0x3d, 0xea, 0xab, 0x16, 0x73, 0x6b,
	0x94, 0xf0, 0x2f, 0xcc, 0xbf, 0x09, 0x88, 0x7f, 0x6b, 0x5b, 0xc4, 0x25, 0xc1, 0xf5, 0x43, 0x90,
	0xc5, 0x28, 0xf7, 0x99, 0xe3, 0x39, 0x26, 0x25, 0x35, 0xef, 0x66, 0x58, 0x33, 0x3d, 0x3b, 0xa8,
	0xa5, 0xc5, 0xc2, 0x75, 0xf2, 0x95, 0xcf, 0x22, 0x71, 0xc5, 0x9d, 0x1f, 0x02, 0x94, 0x3a, 0xc4,
	0xba, 0x36, 0xa9, 0x1d, 0xb8, 0x68, 0x1f, 0xf2, 0x61, 0x6b, 0xb2, 0xb0, 0x2d, 0x54, 0x57, 0xeb,
	0x5b, 0xea, 0x74, 0xeb, 0xea, 0x3d, 0x55, 0x1f, 0x7b, 0x44, 0x8b, 0xc8, 0xe8, 0x04, 0xc0, 0x33,
	0x7d, 0xd3, 0x25, 0x9c, 0xf8, 0x81, 0x2c, 0x6e, 0xe7, 0xaa, 0xe5, 0xfa, 0x8b, 0x39, 0x52, 0xf5,
	0xec, 0x9e, 0x8d, 0x29, 0xf7, 0xc7, 0x5a, 0x46, 0xae, 0xbc, 0x85, 0xca, 0xd4, 0x32, 0x92, 0x20,
	0x77, 0x43, 0xc6, 0x51, 0x4f, 0x25, 0x2d, 0xfc, 0x8b, 0x36, 0xa0, 0x70, 0x6b, 0x3a, 0x23, 0x22,
	0x8b, 0x11, 0x16, 0x7f, 0xbc, 0x11, 0x5f, 0x0b, 0x3b, 0x3f, 0xf3, 0x00, 0x87, 0xf7, 0x35, 0xd1,
	0x2a, 0x88, 0xf6, 0x20, 0x51, 0x8a, 0xf6, 0x00, 0x3d, 0x87, 0x4a, 0x92, 0xa1, 0x91, 0x84, 0x98,
	0x58, 0xac, 0x26, 0x70, 0x2f, 0x46, 0xd1, 0x01, 0x94, 0xdc, 0xbb, 0x7e, 0xe5, 0xdc, 0xb6, 0x50,
	0x2d, 0xd7, 0xff, 0x9d, 0xb3, 0x25, 0x2d, 0x65, 0xa3, 0x77, 0xb0, 0x98, 0x44, 0x2c, 0xe7, 0x23,
	0xe1, 0xae, 0x3a, 0x1b, 0x7e, 0xda, 0xe3, 0x61, 0x8c, 0x68, 0x77, 0x22, 0xf4, 0x1e, 0x8a, 0x8e,
	0xd9, 0x27, 0x4e, 0x20, 0x17, 0xa2, 0x28, 0xab, 0xb3, 0x75, 0x53, 0xb5, 0xda, 0x8e, 0xa8, 0x71,
	0x8e, 0x89, 0x0e, 0xbd, 0x84, 0x42, 0xc0, 0x4d, 0x4e, 0xe4, 0x62, 0x34, 0xc6, 0xbf, 0x67, 0x0d,
	0x7a, 0xe1, 0xb2, 0x16, 0xb3, 0x50, 0x1b, 0x9e, 0x06, 0x6c, 0xe4, 0x5b, 0xc4, 0x98, 0xca, 0xc6,
	0x70, 0x4d, 0x6a, 0x0e, 0x89, 0x6f, 0x50, 0xd3, 0x25, 0xf2, 0x62, 0x14, 0xd4, 0x56, 0x4c, 0xed,
	0x4e, 0xc4, 0xd5, 0x89, 0x79, 0x5d, 0xd3, 0x25, 0xe8, 0x02, 0xaa, 0x03, 0x12, 0x70, 0x9b, 0x9a,
	0x61, 0xa5, 0xf9, 0x96, 0x4b, 0x91, 0xe5, 0x6e, 0x86, 0xff, 0x7b, 0xdf, 0x06, 0xfc, 0x3f, 0xed,
	0x45, 0xe8, 0xc0, 0x63, 0x36, 0xe5, 0xb1, 0x59, 0x29, 0x32, 0x53, 0x26, 0x07, 0x89, 0x13, 0x4a,
	0x68, 0xa1, 0x1c, 0x40, 0x39, 0x13, 0xd7, 0x1f, 0x9d, 0xab, 0x6f, 0x22, 0x54, 0xd2, 0xd4, 0xf1,
	0x2d, 0xa1, 0x1c, 0x1d, 0x4c, 0x5c, 0x96, 0x67, 0xf3, 0xc6, 0x14, 0x09, 0x32, 0x57, 0x46, 0x87,
	0x72, 0xca, 0xbb, 0xbb, 0x33, 0xf5, 0x47, 0x1d, 0x32, 0xdf, 0xc9, 0xc8, 0xb3, 0x36, 0xca, 0x67,
	0x90, 0xa6, 0x09, 0x0f, 0x6c, 0xb2, 0x9e, 0xdd, 0x64, 0xb9, 0xfe, 0xdf, 0xbc, 0xaa, 0x99, 0x08,
	0xf6, 0xbe, 0x0b, 0xb0, 0x32, 0x71, 0xfd, 0xd1, 0x5f, 0xb0, 0xd6, 0xc4, 0x47, 0x8d, 0xf3, 0xb6,
	0x6e, 0xb4, 0xba, 0x3a, 0xd6, 0x8e, 0x1a, 0x87, 0x58, 0x5a, 0x40, 0x1b, 0x20, 0x9d, 0x60, 0xad,
	0x8b, 0xdb, 0x19, 0x54, 0x40, 0xeb, 0x50, 0xb9, 0x38, 0x3e, 0xed, 0x65, 0xa9, 0x22, 0x5a, 0x83,
	0x95, 0x0e, 0xee, 0x64, 0xa0, 0x5c, 0xc8, 0xeb, 0x69, 0xad, 0xd3, 0x8b, 0x0c, 0x98, 0x47, 0x12,
	0x2c, 0x1f, 0x5f, 0x66, 0x90, 0xc2, 0xde, 0x3f, 0x50, 0x88, 0x0e, 0x31, 0x2a, 0x82, 0x78, 0x7e,
	0x26, 0x2d, 0xa0, 0x25, 0xc8, 0x37, 0x4f, 0x2f, 0xbb, 0x92, 0xb0, 0xd7, 0x82, 0xf5, 0x07, 0x92,
	0x47, 0x0a, 0x6c, 0xb6, 0xba, 0x2d, 0xbd, 0xd5, 0x68, 0x1b, 0x3d, 0xbd, 0xa1, 0x63, 0x43, 0xd7,
	0x1a, 0xdd, 0xde, 0x11, 0xd6, 0xa4, 0x05, 0x04, 0x50, 0x3c, 0x3f, 0x6b, 0x36, 0xf4, 0xb0, 0x51,
	0x80, 0x62, 0x13, 0xb7, 0xb1, 0x8e, 0x25, 0xb1, 0x7e, 0x05, 0x6b, 0x1d, 0x46, 0x6d, 0xce, 0xfc,
	0xcc, 0xa3, 0xf2, 0x11, 0xd0, 0x0c, 0x18, 0xa0, 0x4d, 0x75, 0xc8, 0xd8, 0xd0, 0x21, 0xf1, 0xbb,
	0xda, 0x1f, 0x5d, 0xa9, 0x38, 0x7c, 0xd8, 0x95, 0x27, 0x8f, 0x4e, 0xf5, 0x95, 0xf0, 0x61, 0xf9,
	0x13, 0xa4, 0xeb, 0xfd, 0x62, 0x64, 0xb1, 0xff, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x4c, 0x6f,
	0x4f, 0x4c, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MonitorConnectionClient is the client API for MonitorConnection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitorConnectionClient interface {
	MonitorConnections(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (MonitorConnection_MonitorConnectionsClient, error)
}

type monitorConnectionClient struct {
	cc *grpc.ClientConn
}

func NewMonitorConnectionClient(cc *grpc.ClientConn) MonitorConnectionClient {
	return &monitorConnectionClient{cc}
}

func (c *monitorConnectionClient) MonitorConnections(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (MonitorConnection_MonitorConnectionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MonitorConnection_serviceDesc.Streams[0], "/local.connection.MonitorConnection/MonitorConnections", opts...)
	if err != nil {
		return nil, err
	}
	x := &monitorConnectionMonitorConnectionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MonitorConnection_MonitorConnectionsClient interface {
	Recv() (*ConnectionEvent, error)
	grpc.ClientStream
}

type monitorConnectionMonitorConnectionsClient struct {
	grpc.ClientStream
}

func (x *monitorConnectionMonitorConnectionsClient) Recv() (*ConnectionEvent, error) {
	m := new(ConnectionEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MonitorConnectionServer is the server API for MonitorConnection service.
type MonitorConnectionServer interface {
	MonitorConnections(*empty.Empty, MonitorConnection_MonitorConnectionsServer) error
}

// UnimplementedMonitorConnectionServer can be embedded to have forward compatible implementations.
type UnimplementedMonitorConnectionServer struct {
}

func (*UnimplementedMonitorConnectionServer) MonitorConnections(req *empty.Empty, srv MonitorConnection_MonitorConnectionsServer) error {
	return status.Errorf(codes.Unimplemented, "method MonitorConnections not implemented")
}

func RegisterMonitorConnectionServer(s *grpc.Server, srv MonitorConnectionServer) {
	s.RegisterService(&_MonitorConnection_serviceDesc, srv)
}

func _MonitorConnection_MonitorConnections_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MonitorConnectionServer).MonitorConnections(m, &monitorConnectionMonitorConnectionsServer{stream})
}

type MonitorConnection_MonitorConnectionsServer interface {
	Send(*ConnectionEvent) error
	grpc.ServerStream
}

type monitorConnectionMonitorConnectionsServer struct {
	grpc.ServerStream
}

func (x *monitorConnectionMonitorConnectionsServer) Send(m *ConnectionEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _MonitorConnection_serviceDesc = grpc.ServiceDesc{
	ServiceName: "local.connection.MonitorConnection",
	HandlerType: (*MonitorConnectionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MonitorConnections",
			Handler:       _MonitorConnection_MonitorConnections_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "connection.proto",
}
